i.TH "include/count.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/count.h - Returns the number of times a specified value occurs in a string
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcount\fP (const char *str, const char *sub)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int count (const char * str, const char * sub)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
