.TH "include/endswith.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/endswith.h - Returns true if the string ends with the specified value
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBendswith\fP (const char *str, const char last_char)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int endswith (const char * str, const char last_char)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
