.TH "src/isallnum.c" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/isallnum.c - Returns True if all characters in the string are alphanumeric
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include '\&.\&./include/length\&.h'\fP
.br
\fR#include '\&.\&./include/isallnum\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisallnum\fP (const char *str)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBSMALL_L\fP [\fBL_COUNT\fP]"
.br
.ti -1c
.RI "const char \fBCAPITAL_L\fP [\fBL_COUNT\fP]"
.br
.ti -1c
.RI "const char \fBNUMS\fP [10]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isallnum (const char * str)"

.SH "Variable Documentation"
.PP 
.SS "const char CAPITAL_L[\fBL_COUNT\fP]\fR [extern]\fP"

.SS "const char NUMS[10]\fR [extern]\fP"

.SS "const char SMALL_L[\fBL_COUNT\fP]\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
