.TH "include/isuppercase.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/isuppercase.h - Returns True if all characters in the string are upper case
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBL_COUNT\fP   26"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisuppercase\fP (const char *str)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define L_COUNT   26"

.SH "Function Documentation"
.PP 
.SS "int isuppercase (const char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
