.TH "src/join.c" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/join.c - Converts the elements of an iterable into a string
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <signal\&.h>\fP
.br
\fR#include '\&.\&./include/length\&.h'\fP
.br
\fR#include '\&.\&./include/helper_func/err_\&.h'\fP
.br
\fR#include '\&.\&./include/join\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBjoin\fP (const char *arr[], const unsigned int len, const char sep)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * join (const char * arr[], const unsigned int len, const char sep)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
