.TH "include/join.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/join.h - Converts the elements of an iterable into a string
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBjoin\fP (const char *arr[], const unsigned int len, const char sep)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * join (const char * arr[], const unsigned int len, const char sep)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
