.TH "src/ljust.c" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ljust.c - Returns a left justified version of the string
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include '\&.\&./include/helper_func/err_\&.h'\fP
.br
\fR#include '\&.\&./include/length\&.h'\fP
.br
\fR#include '\&.\&./include/ljust\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBljust\fP (const char *str, const unsigned int width)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ljust (const char * str, const unsigned int width)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
