.TH "src/replace.c" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/replace.c - Returns a string where a specified value is replaced with a specified value
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include '\&.\&./include/length\&.h'\fP
.br
\fR#include '\&.\&./include/find\&.h'\fP
.br
\fR#include '\&.\&./include/replace\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBreplace\fP (const char *str, const char *s1, const char *s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * replace (const char * str, const char * s1, const char * s2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
