.TH "src/rfind.c" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rfind.c - Searches the string for a specified value and returns the last position of where it was found
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include '\&.\&./include/length\&.h'\fP
.br
\fR#include '\&.\&./include/rfind\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrfind\fP (const char *str, const char *sub)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int rfind (const char * str, const char * sub)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
