.TH "include/rjust.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/rjust.h - Returns a right justified version of the string
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBrjust\fP (const char *str, const unsigned int width)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * rjust (const char * str, const unsigned int width)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
