.TH "include/rstrip.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/rstrip.h - Returns a right trim version of the string
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBrstrip\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * rstrip (const char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
