.TH "include/split.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/split.h - Splits the string at the specified separator, and returns a list
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBsplit\fP (const char *str, unsigned int *s, const char sep)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char ** split (const char * str, unsigned int * s, const char sep)"

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
