.TH "src/stringsjustlikepython.c" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/stringsjustlikepython.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/stringsjustlikepython\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
