.TH "include/stringsjustlikepython.h" 3 "Version 5.1" "StringsJustLikePython" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/stringsjustlikepython.h
.SH SYNOPSIS
.br
.PP
\fR#include 'capitalize\&.h'\fP
.br
\fR#include 'length\&.h'\fP
.br
\fR#include 'lower\&.h'\fP
.br
\fR#include 'center\&.h'\fP
.br
\fR#include 'endswith\&.h'\fP
.br
\fR#include 'find\&.h'\fP
.br
\fR#include 'isdecimal\&.h'\fP
.br
\fR#include 'isallpha\&.h'\fP
.br
\fR#include 'isidentifier\&.h'\fP
.br
\fR#include 'isallnum\&.h'\fP
.br
\fR#include 'islowercase\&.h'\fP
.br
\fR#include 'iswhitespace\&.h'\fP
.br
\fR#include 'istitle\&.h'\fP
.br
\fR#include 'isuppercase\&.h'\fP
.br
\fR#include 'join\&.h'\fP
.br
\fR#include 'upper\&.h'\fP
.br
\fR#include 'ljust\&.h'\fP
.br
\fR#include 'rjust\&.h'\fP
.br
\fR#include 'split\&.h'\fP
.br
\fR#include 'startswith\&.h'\fP
.br
\fR#include 'strip\&.h'\fP
.br
\fR#include 'lstrip\&.h'\fP
.br
\fR#include 'rstrip\&.h'\fP
.br
\fR#include 'swapcase\&.h'\fP
.br
\fR#include 'zfill\&.h'\fP
.br
\fR#include 'count\&.h'\fP
.br
\fR#include 'replace\&.h'\fP
.br
\fR#include 'title\&.h'\fP
.br
\fR#include 'rfind\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StringsJustLikePython from the source code\&.
